name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12' # FALHA 7: Versão do Node.js antiga e incompatível. A pipeline vai quebrar aqui.

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run Tests
        run: |
          cd backend
          npm test

      # FALHA 8: Faltam os passos de Build do Frontend e Build das Imagens Docker.